{
  "version": 3,
  "sources": [
    "../counter.py"
  ],
  "mappings": ";;;;;;;;;;;;;;;;;;;;AAKQ;AAAe;AAAf;AAGM;;AAAN;;;AAaA;AAAA;AAAA;AAAA;AAAgB;AAAhB;AAAA;AAAA;AAAA;AAVe;;AAGA;",
  "op_pc_offset": 0,
  "pc_events": {
    "31": {
      "error": "check self.counter exists"
    }
  }
}